name: Build (CI)

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]
  push:
    branches: [main]
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: yarn  

      - name: Build
        run: yarn run build

  release_note:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Do not persist credentials to access the repository

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Specify Node.js 20.x

      - name: Install Packages
        run: yarn 

      - name: Generate Note
        run: yarn run semantic-release